<?php
        /**网站缓存配置文件**/


return [
        "sitename"=>"V5朕玥传媒",
                "cachetime"=>"100",
                "videourl"=>"video/video.mov",
                "pagesize"=>"50",
                "msgshowtime"=>"1000",
                "logo"=>"logo.png",
                "watermark"=>"watermark.png",
                "thumbsize"=>"100*100",
                "filepath"=>"files",
                "domain"=>"http://m.olrea.net",
                "waterposition"=>"bottom-right",
                "water"=>"关闭",
                "closelayer"=>"开启",
                "editor"=>"u-editor",
                "Template"=>"default",
                "ShouYiRate"=>"日",
                "LoginCode"=>"off",
                "XiaXianReg"=>"98",
                "withdrawalbalance"=>"100",
                "withdrawalmin"=>"200",
                "qiandao"=>"2",
                "newmess"=>"尊敬的{username}会员您好！欢迎您注册使用本网站。有什么不明白的请联系在线客服。【岳赢投资】",
                "gg"=>"尊敬的新老会员：推荐朋友投资，通过您的推广代码注册，您推荐的朋友充值并成功投资项目，您可以得到3%的佣金奖励。比如您介绍充值10000元，您可得到提成300元。依此类推！",
                "AppDownloadUrl"=>"https://app.seolrea.net/sad",
                "smsverifi"=>"关闭",
                "APPErwmbj"=>"APPErwmbj.png",
                "playSound"=>"关闭",
                "title"=>"V5电影投资-影视投资分红-影视投资项目投资平台",
                "keywords"=>"全网最专业的理财平台",
                "description"=>"朕玥文化传媒（北京）有限公司办公室地址位于中国的首都，政治、文化中心北京，北京 北京市朝阳区朝阳路67号8号楼2层203，于2013年10月24日在朝阳分局注册成立，注册资本为1000 万元 人民币，在公司发展壮大的6年里，我们始终为客户提供好的产品和技术支持、健全的售后服务，我公司主要经营广播电视节目制作；...组织文化艺术交流活动（不含演出）；代理、发布广告；影视策划；文艺创作；摄影服务。（企业依法自主选择经营项目，开展经营活动；电影发行、广播电视节目制作以及依法须经批准的项目，经相关部门批准后依批准的内容开展经营活动；不得从事本市产业政策禁止和限制类项目的经营活动。，我们有好的产品和专业的销售和技术团队，我公司属于北京文化艺术业黄页行业，如果您对我公司的产品服务有兴趣，期待您在线留言或者来电咨询",
                "AttemptLogin"=>"5",
                "CompanyLong"=>"V5文化传媒（北京）有限公司",
                "smsappid"=>"dbd4709934bcedcb4cc834dbec0ac667",
                "smspass"=>"dbd4709934bcedcb4cc834dbec0ac667",
                "offiseal"=>"offiseal.png",
                "pcpagesize"=>"10",
                "waplogo"=>"waplogo.png",
                "Openmode"=>"pc+wap",
                "mbanner"=>"/uploads/files/20190621/15610495405d0bb9c40126b.jpg,/uploads/files/20190621/15610495975d0bb9fd644eb.jpg,/uploads/files/20190621/15610496065d0bba068f3cf.jpg",
                "CompanyShort"=>"朕玥传媒",
                "AccessPrivileges"=>"开启",
                "lotterypoint"=>"0",
                "webmsgtype"=>"充值|提款|项目本金返款|加入项目|每日签到|项目分红|下线项目分红|下线购买分成|冻结资金|解冻资金|扣款|复利返息|复利复投||等级奖励|余额宝奖励|余额宝转入|余额宝转出|大转盘|通知|现金券|加息券",
                "videoopen"=>"关闭",
                "RechargeType"=>"系统充值|优惠活动|优惠充值|后台充值|用户充值",
                "FengHongDateFormat"=>"Y-m-d H:i:s",
                "UserMsgSound"=>"开启",
                "codetitle"=>"金融理财    走向全国",
                "LoginJump"=>"会员中心",
                "IndexHoudong"=>"关闭",
                "DefaultRecCode"=>"5135667",
                "WapTemplate"=>"bluev3",
                "lotterysbg"=>"lotterysbg.jpg",
                "PcTemplate"=>"financev2",
                "pclogo"=>"pclogo.png",
                "kefuqq"=>"67406722",
                "fuwurexian"=>"400027063",
                "webbeian"=>"京ICP备13053222号-13",
                "kefumail"=>"67406722@qq.com",
                "gongsidizhi"=>"北京市朝阳区朝阳路67号8号楼2层203",
                "gongzuoshijian"=>"9:00-22:00",
                "RegisteredIP"=>"关闭",
                "pccode"=>"<script></script>",
                "BoxOffice"=>"关闭",
                "accountingfirm"=>"普华永道(PWC)会计师事务所和上海申京律师事务所(项目)",
                "wapcode"=>"<script></script>",
                "YuBaoLv"=>"0.05",
                "YuBaoLvMH"=>"100000",
                "YuBaoLvML"=>"100",
                "rename"=>"关闭",
                "IdCardAppCode"=>"ce0d3b5006a3b18b1ed963f4444d",
                "imName"=>"在线客服",
                "WebIMKeFu"=>"关闭",
                "TouziTikuai"=>"所有",
                "OfficialSeal"=>"图片章",
                "AutoSendMsg"=>"自动",
                "ProductBackgroundA"=>"background: #ff9900;",
                "ProductBackgroundB"=>"background: #C102CD;",
                "supervise"=>"上海银行提供监管(项目)",
                "boxgg"=>"首页弹窗公告",
                "MemberLockingMsg"=>"请联系客服",
                "TaotiaoIndexOn"=>"关闭",
                "appdownloge"=>"appdownloge.png",
                "waptongjicode"=>"<script type='text/javascript' src='//js.users.51.la/20645681.js'></script>",
                "IndexTaotiaoAppText"=>"投资理财<br/>头条新闻APP",
                "IndexTaotiaoAppTitle"=>"合略生活",
                "RealNameOnly"=>"关闭",
                "DividendsYesterday"=>"56800",
                "NoticTipTxt2"=>"<li><b>①周末签到2.2元，幸运转转转最高可获取588元现金</b></li>
<li><b>②青铜级别以上会员赠送1次抽奖机会(奖品588元)</b></li>
<li><b>③银行入款5千返回1%起，8万返2%起；</b></li>",
                "RegisterCoupon"=>"5",
                "RealnameCoupon"=>"4",
                "InvitationCoupon"=>"0",
                "CouponGiveOn"=>"开启",
                

        ];